version: '3.9'

services:
  api:
    build: .
    container_name: thai-gold-api
    ports:
      - "3000:3000"
    environment:
      TRACK_API_URL: ${TRACK_API_URL}
      UMAMI_WEBSITE_NAME: ${UMAMI_WEBSITE_NAME}
      UMAMI_WEBSITE_DOMAIN: ${UMAMI_WEBSITE_DOMAIN}
    restart: always
    env_file:
      - .env

  frontend:
    build:
      context: ./my-project
    container_name: thai-gold-frontend
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./my-project:/app          # your source code for live-reload
      - /app/node_modules         # anonymous volume → keeps the container’s own modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    restart: always
